/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BaiThucHanhChuong2Ngay220826;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author PC DELL
 */
public class JFrameQuanLySanPham extends javax.swing.JFrame {

    private ArrayList<SanPham> danhSach = new ArrayList<>();

    /**
     * Creates new form JFrameQuanLySanPham
     */
    public JFrameQuanLySanPham() {
        initComponents();
        setLocationRelativeTo(null);
        txtDonGia.setEnabled(false);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tableSanPham.setDefaultRenderer(Object.class, centerRenderer);

        ((DefaultTableCellRenderer) tableSanPham.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    }

    private SanPham layThongTin() {
        String maSP = txtMaSP.getText().trim();
        String tenSP = txtTenSP.getText().trim();
        int soLuong = Integer.parseInt(txtSoLuong.getText().trim());

        return new SanPham(maSP, tenSP, soLuong);
    }

    private boolean kiemTraMaSP(String maSP) {
        return maSP.matches("(?=.*[a-zA-Z])(?=.*[0-9])[a-zA-Z0-9]{1,5}");
    }

    private boolean trungMaSP(String maSP) {
        for (SanPham sp : danhSach) {
            if (sp.getMaSP().equalsIgnoreCase(maSP)) {
                return true;
            }
        }

        return false;
    }

    private void hienThiDanhSach() {
        DefaultTableModel model = (DefaultTableModel) tableSanPham.getModel();

        model.setRowCount(0);

        for (SanPham sp : danhSach) {
            model.addRow(new Object[]{
                sp.getMaSP(),
                sp.getTenSP(),
                sp.getSoLuong(),
                sp.getDonGia(),
                sp.getTienHang()
            });
        }
    }

    private void xoaTrang() {
        txtMaSP.setText("");
        txtTenSP.setText("");
        txtSoLuong.setText("");
        txtDonGia.setText("");

        // Trạng thái nhập mới
        txtMaSP.setEnabled(true);
        txtTenSP.setEnabled(true);
        txtSoLuong.setEnabled(true);

        // Đơn giá luôn bị khóa
        txtDonGia.setEnabled(false);

        txtMaSP.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtMaSP = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSanPham = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnLamMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý kho hàng(Sản phẩm)");

        jLabel1.setText("Mã sản phẩm:");

        jLabel2.setText("Tên sản phẩm:");

        jLabel3.setText("Số lượng:");

        jLabel4.setText("Đơn Giá:");

        btnThem.setBackground(new java.awt.Color(0, 204, 0));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(0, 153, 153));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 51, 51));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Hàng", "Tên Hàng", "Số Lượng", "Đơn Giá", "Tiền hàng"
            }
        ));
        tableSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSanPhamMouseClicked(evt);
            }
        });
        tableSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableSanPhamKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableSanPham);

        jLabel5.setText("Thông tin sản phẩm");

        btnLamMoi.setBackground(new java.awt.Color(204, 204, 255));
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnSua)
                            .addComponent(btnXoa))
                        .addGap(18, 18, 18)
                        .addComponent(btnLamMoi)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:                                                                              
        try {
            String maSP = txtMaSP.getText().trim();
            String tenSP = txtTenSP.getText().trim();
            String soLuongText = txtSoLuong.getText().trim();

            if (maSP.isEmpty() || tenSP.isEmpty() || soLuongText.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Vui lòng nhập đầy đủ thông tin!");
                return;
            }

            // Kiểm tra mã phải có cả chữ và số, tối đa 5 ký tự
            if (!kiemTraMaSP(maSP)) {
                JOptionPane.showMessageDialog(this,
                        "Mã hàng phải có cả chữ và số, tối đa 5 ký tự!");
                return;
            }

            // Kiểm tra mã trùng
            if (trungMaSP(maSP)) {
                JOptionPane.showMessageDialog(this,
                        "Mã hàng đã tồn tại!");
                return;
            }

            int soLuong = Integer.parseInt(soLuongText);

            if (soLuong < 0) {
                JOptionPane.showMessageDialog(this,
                        "Số lượng không được âm!");
                return;
            }

            // Tạo sản phẩm
            SanPham sp = new SanPham(maSP, tenSP, soLuong);

            danhSach.add(sp);

            // Hiển thị lên bảng
            hienThiDanhSach();

            // Hiển thị đơn giá tự động
            txtDonGia.setText(String.valueOf(sp.getDonGia()));

            JOptionPane.showMessageDialog(this,
                    "Thêm sản phẩm thành công!");

            // Sau khi thêm thì cho phép nhập mã mới
            xoaTrang();

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                    "Số lượng phải là số!");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:                                                                           
        try {
            String maSP = txtMaSP.getText().trim();
            String tenSP = txtTenSP.getText().trim();
            String soLuongText = txtSoLuong.getText().trim();

            if (maSP.isEmpty() || tenSP.isEmpty() || soLuongText.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Vui lòng nhập đầy đủ thông tin!");
                return;
            }

            int soLuong = Integer.parseInt(soLuongText);

            if (soLuong < 0) {
                JOptionPane.showMessageDialog(this,
                        "Số lượng không được âm!");
                return;
            }

            // Tìm sản phẩm theo mã
            for (SanPham sp : danhSach) {

                if (sp.getMaSP().equalsIgnoreCase(maSP)) {

                    // CHỈ sửa tên và số lượng
                    sp.setTenSP(tenSP);
                    sp.setSoLuong(soLuong);

                    // Đơn giá tự động thay đổi theo số lượng
                    txtDonGia.setText(String.valueOf(sp.getDonGia()));

                    // Cập nhật JTable
                    hienThiDanhSach();

                    JOptionPane.showMessageDialog(this,
                            "Sửa sản phẩm thành công!");

                    return;
                }
            }

            JOptionPane.showMessageDialog(this,
                    "Không tìm thấy sản phẩm!");

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                    "Số lượng phải là số!");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:                                       
        String maSP = txtMaSP.getText().trim();

        if (maSP.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Vui lòng nhập mã sản phẩm cần xóa!");
            return;
        }

        for (int i = 0; i < danhSach.size(); i++) {

            if (danhSach.get(i).getMaSP().equalsIgnoreCase(maSP)) {

                int luaChon = JOptionPane.showConfirmDialog(
                        this,
                        "Bạn có chắc muốn xóa sản phẩm này?",
                        "Xác nhận",
                        JOptionPane.YES_NO_OPTION
                );

                if (luaChon == JOptionPane.YES_OPTION) {

                    danhSach.remove(i);

                    hienThiDanhSach();

                    JOptionPane.showMessageDialog(this,
                            "Xóa sản phẩm thành công!");

                    xoaTrang();

                }

                return;
            }
        }

        JOptionPane.showMessageDialog(this,
                "Không tìm thấy mã sản phẩm!");
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        xoaTrang();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void tableSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSanPhamMouseClicked
        // TODO add your handling code here:
        int row = tableSanPham.getSelectedRow();

        if (row >= 0) {
            txtMaSP.setText(tableSanPham.getValueAt(row, 0).toString());
            txtTenSP.setText(tableSanPham.getValueAt(row, 1).toString());
            txtSoLuong.setText(tableSanPham.getValueAt(row, 2).toString());
            txtDonGia.setText(tableSanPham.getValueAt(row, 3).toString());

            // Khi sửa: khóa Mã SP
            txtMaSP.setEnabled(false);

            // Cho sửa Tên SP và Số lượng
            txtTenSP.setEnabled(true);
            txtSoLuong.setEnabled(true);

            // Đơn giá luôn luôn khóa
            txtDonGia.setEnabled(false);
        }
    }//GEN-LAST:event_tableSanPhamMouseClicked

    private void tableSanPhamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableSanPhamKeyReleased
        // TODO add your handling code here:
        int row = tableSanPham.getSelectedRow();

        if (row >= 0) {
            txtMaSP.setText(tableSanPham.getValueAt(row, 0).toString());
            txtTenSP.setText(tableSanPham.getValueAt(row, 1).toString());
            txtSoLuong.setText(tableSanPham.getValueAt(row, 2).toString());
            txtDonGia.setText(tableSanPham.getValueAt(row, 3).toString());

            // Khi sửa: khóa Mã SP
            txtMaSP.setEnabled(false);

            // Cho sửa Tên SP và Số lượng
            txtTenSP.setEnabled(true);
            txtSoLuong.setEnabled(true);

            // Đơn giá luôn luôn khóa
            txtDonGia.setEnabled(false);
        }
    }//GEN-LAST:event_tableSanPhamKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameQuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameQuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameQuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameQuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameQuanLySanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSanPham;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}