/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC DELL
 */

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
public class BaiThucHanhNgay200826 extends javax.swing.JFrame {

    private DefaultTableModel model;
    private ArrayList<Student> danhSachSinhVien = new ArrayList<>();
    private int soLuongDaNhap = 0;
    private int soLuongHocPhanCanNhap = 0;
    private boolean daNhapSoLuong = false;
    /**
     * Creates new form BaiThucHanhNgay200826
     */
    public BaiThucHanhNgay200826() {
        initComponents();
        
        model = new DefaultTableModel();

        model.setColumnIdentifiers(new Object[]{
            "Mã SV",
            "Tên SV",
            "Học phần",
            "Chuyên cần",
            "Giữa kỳ",
            "Cuối kỳ",
            "Tổng kết"
        });

        tableDiem.setModel(model);

        // Ban đầu chưa được nhập thông tin học phần
        txtTenHocPhan.setEnabled(false);
        txtChuyenCan.setEnabled(false);
        txtGiuaKy.setEnabled(false);
        txtCuoiKy.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTenSV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtChuyenCan = new javax.swing.JTextField();
        txtCuoiKy = new javax.swing.JTextField();
        txtGiuaKy = new javax.swing.JTextField();
        txtTenHocPhan = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDiem = new javax.swing.JTable();
        txtMaSV = new javax.swing.JTextField();
        txtSoLuongHocPhan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tên Sinh Viên:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("QUẢN LÝ ĐIỂM SINH VIÊN");

        jLabel3.setText("Nhập điểm cc:");

        jLabel4.setText("Nhập điểm giữa kỳ:");

        jLabel5.setText("Nhập điểm cuối kỳ:");

        jLabel6.setText("Nhập tên học phần:");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jLabel9.setText("Thông tin điểm học phần");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtChuyenCan, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtGiuaKy, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTenHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCuoiKy, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLamMoi))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel9)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtChuyenCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiuaKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCuoiKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnLamMoi))
                .addGap(47, 47, 47))
        );

        tableDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sinh Viên", "Tên Sinh Viên", "Điểm CC", "Điểm Giữa Kỳ", "Điểm Cuối Kỳ", "Điểm Tổng Kết", "Học Phần"
            }
        ));
        tableDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDiem);

        jLabel7.setText("Mã Sinh Viên:");

        jLabel8.setText("Nhập số lượng HP: ");

        jLabel10.setText("Thông tin sinh viên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel7))
                                        .addGap(49, 49, 49)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoLuongHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(151, 151, 151)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoLuongHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
                                    
        try {

            String maSV = txtMaSV.getText().trim();
            String tenSV = txtTenSV.getText().trim();

            if (!daNhapSoLuong) {

                if (maSV.isEmpty()
                        || tenSV.isEmpty()
                        || txtSoLuongHocPhan.getText().trim().isEmpty()) {

                    JOptionPane.showMessageDialog(
                            this,
                            "Vui lòng nhập Mã SV, Tên SV và Số lượng học phần!"
                    );
                    return;
                }

                // Kiểm tra mã sinh viên đã tồn tại chưa
                for (Student sv : danhSachSinhVien) {

                    if (sv.getMaSV().equals(maSV)) {

                        JOptionPane.showMessageDialog(
                                this,
                                "Mã sinh viên đã tồn tại!"
                        );

                        return;
                    }
                }

                soLuongHocPhanCanNhap = Integer.parseInt(
                        txtSoLuongHocPhan.getText().trim()
                );

                if (soLuongHocPhanCanNhap <= 0) {

                    JOptionPane.showMessageDialog(
                            this,
                            "Số lượng học phần phải lớn hơn 0!"
                    );

                    return;
                }

                // Bắt đầu nhập học phần
                daNhapSoLuong = true;
                soLuongDaNhap = 0;

                // Cho phép nhập học phần
                txtTenHocPhan.setEnabled(true);
                txtChuyenCan.setEnabled(true);
                txtGiuaKy.setEnabled(true);
                txtCuoiKy.setEnabled(true);

                // Khóa thông tin sinh viên
                txtMaSV.setEnabled(false);
                txtTenSV.setEnabled(false);
                txtSoLuongHocPhan.setEnabled(false);

                btnThem.setText("Thêm học phần");

                JOptionPane.showMessageDialog(
                        this,
                        "Đã nhập " + soLuongHocPhanCanNhap
                        + " học phần.\n"
                        + "Hãy nhập thông tin học phần đầu tiên!"
                );

                return;
            }

            // =====================================================
            // BƯỚC 2: NHẬP HỌC PHẦN
            // =====================================================
            String tenHocPhan = txtTenHocPhan.getText().trim();

            if (tenHocPhan.isEmpty()
                    || txtChuyenCan.getText().trim().isEmpty()
                    || txtGiuaKy.getText().trim().isEmpty()
                    || txtCuoiKy.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(
                        this,
                        "Vui lòng nhập đầy đủ tên học phần và điểm!"
                );

                return;
            }

            double chuyenCan = Double.parseDouble(
                    txtChuyenCan.getText().trim()
            );

            double giuaKy = Double.parseDouble(
                    txtGiuaKy.getText().trim()
            );

            double cuoiKy = Double.parseDouble(
                    txtCuoiKy.getText().trim()
            );

            // Kiểm tra điểm
            if (chuyenCan < 0 || chuyenCan > 10
                    || giuaKy < 0 || giuaKy > 10
                    || cuoiKy < 0 || cuoiKy > 10) {

                JOptionPane.showMessageDialog(
                        this,
                        "Điểm phải nằm trong khoảng từ 0 đến 10!"
                );

                return;
            }

            // =====================================================
            // TÌM SINH VIÊN
            // =====================================================
            Student sinhVien = null;

            for (Student sv : danhSachSinhVien) {

                if (sv.getMaSV().equals(maSV)) {

                    sinhVien = sv;

                    break;
                }
            }

            // Nếu chưa có thì tạo sinh viên mới
            if (sinhVien == null) {

                sinhVien = new Student(maSV, tenSV);

                danhSachSinhVien.add(sinhVien);
            }

            // =====================================================
            // TẠO HỌC PHẦN
            // =====================================================
            HocPhan hp = new HocPhan(
                    tenHocPhan,
                    chuyenCan,
                    giuaKy,
                    cuoiKy
            );

            sinhVien.themHocPhan(hp);

            // Thêm vào bảng
            model.addRow(new Object[]{
                sinhVien.getMaSV(),
                sinhVien.getTenSV(),
                hp.getTenHocPhan(),
                hp.getDiemChuyenCan(),
                hp.getDiemGiuaKy(),
                hp.getDiemCuoiKy(),
                String.format(
                "%.2f",
                hp.tinhDiemTongKet()
                )
            });

            soLuongDaNhap++;

            // Xóa ô học phần để nhập tiếp
            txtTenHocPhan.setText("");
            txtChuyenCan.setText("");
            txtGiuaKy.setText("");
            txtCuoiKy.setText("");

            // =====================================================
            // ĐÃ NHẬP ĐỦ HỌC PHẦN
            // =====================================================
            if (soLuongDaNhap >= soLuongHocPhanCanNhap) {

                JOptionPane.showMessageDialog(
                        this,
                        "Đã nhập đủ "
                        + soLuongHocPhanCanNhap
                        + " học phần!"
                );

                // Khóa phần học phần
                txtTenHocPhan.setEnabled(false);
                txtChuyenCan.setEnabled(false);
                txtGiuaKy.setEnabled(false);
                txtCuoiKy.setEnabled(false);

                // Cho phép nhập sinh viên mới
                txtMaSV.setEnabled(true);
                txtTenSV.setEnabled(true);
                txtSoLuongHocPhan.setEnabled(true);

                btnThem.setEnabled(true);
                btnThem.setText("Thêm");

                // Reset trạng thái
                daNhapSoLuong = false;
                soLuongDaNhap = 0;
                soLuongHocPhanCanNhap = 0;

                // Xóa thông tin sinh viên cũ
                txtMaSV.setText("");
                txtTenSV.setText("");
                txtSoLuongHocPhan.setText("");

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Thêm học phần thành công!\n"
                        + "Đã nhập: "
                        + soLuongDaNhap
                        + "/"
                        + soLuongHocPhanCanNhap
                        + " học phần."
                );
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Số lượng học phần và điểm phải là số!"
            );
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed

        int row = tableDiem.getSelectedRow();

        if (row == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng chọn sinh viên cần sửa!"
            );

            return;
        }

        try {

            // Lấy mã SV từ bảng
            String maSV = model.getValueAt(row, 0).toString();

            String tenSVMoi = txtTenSV.getText().trim();
            String tenHocPhanMoi = txtTenHocPhan.getText().trim();

            if (tenSVMoi.isEmpty()
                    || tenHocPhanMoi.isEmpty()) {

                JOptionPane.showMessageDialog(
                        this,
                        "Tên sinh viên và tên học phần không được để trống!"
                );

                return;
            }

            double chuyenCanMoi = Double.parseDouble(
                    txtChuyenCan.getText().trim()
            );

            double giuaKyMoi = Double.parseDouble(
                    txtGiuaKy.getText().trim()
            );

            double cuoiKyMoi = Double.parseDouble(
                    txtCuoiKy.getText().trim()
            );

            // Kiểm tra điểm
            if (chuyenCanMoi < 0 || chuyenCanMoi > 10
                    || giuaKyMoi < 0 || giuaKyMoi > 10
                    || cuoiKyMoi < 0 || cuoiKyMoi > 10) {

                JOptionPane.showMessageDialog(
                        this,
                        "Điểm phải từ 0 đến 10!"
                );

                return;
            }

            // Tìm sinh viên
            Student sinhVien = null;

            for (Student sv : danhSachSinhVien) {

                if (sv.getMaSV().equals(maSV)) {

                    sinhVien = sv;

                    break;
                }
            }

            if (sinhVien == null) {

                JOptionPane.showMessageDialog(
                        this,
                        "Không tìm thấy sinh viên!"
                );

                return;
            }

            // Sửa tên sinh viên
            sinhVien.setTenSV(tenSVMoi);

            // Lấy tên học phần cũ
            String tenHocPhanCu
                    = model.getValueAt(row, 2).toString();

            // Tìm học phần
            HocPhan hocPhanCanSua = null;

            for (HocPhan hp : sinhVien.getDanhSachHocPhan()) {

                if (hp.getTenHocPhan()
                        .equals(tenHocPhanCu)) {

                    hocPhanCanSua = hp;

                    break;
                }
            }

            if (hocPhanCanSua == null) {

                JOptionPane.showMessageDialog(
                        this,
                        "Không tìm thấy học phần!"
                );

                return;
            }

            // Sửa học phần
            hocPhanCanSua.setTenHocPhan(
                    tenHocPhanMoi
            );

            hocPhanCanSua.setDiemChuyenCan(
                    chuyenCanMoi
            );

            hocPhanCanSua.setDiemGiuaKy(
                    giuaKyMoi
            );

            hocPhanCanSua.setDiemCuoiKy(
                    cuoiKyMoi
            );

            // Cập nhật TẤT CẢ dòng của sinh viên
            for (int i = 0; i < model.getRowCount(); i++) {

                if (model.getValueAt(i, 0)
                        .toString()
                        .equals(maSV)) {

                    model.setValueAt(
                            tenSVMoi,
                            i,
                            1
                    );
                }
            }

            // Cập nhật dòng đang chọn
            model.setValueAt(
                    tenHocPhanMoi,
                    row,
                    2
            );

            model.setValueAt(
                    chuyenCanMoi,
                    row,
                    3
            );

            model.setValueAt(
                    giuaKyMoi,
                    row,
                    4
            );

            model.setValueAt(
                    cuoiKyMoi,
                    row,
                    5
            );

            model.setValueAt(
                    String.format(
                            "%.2f",
                            hocPhanCanSua.tinhDiemTongKet()
                    ),
                    row,
                    6
            );

            JOptionPane.showMessageDialog(
                    this,
                    "Sửa thành công!"
            );

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Điểm phải là số!"
            );
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:                                                                          

        int row = tableDiem.getSelectedRow();

        if (row == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng chọn sinh viên cần xóa!"
            );

            return;
        }

        String maSV = model.getValueAt(row, 0).toString();
        String tenSV = model.getValueAt(row, 1).toString();

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc muốn xóa sinh viên:\n"
                + maSV + " - " + tenSV
                + "\n\nToàn bộ học phần của sinh viên này cũng sẽ bị xóa!",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // Xóa trong ArrayList
        for (int i = 0; i < danhSachSinhVien.size(); i++) {

            if (danhSachSinhVien.get(i)
                    .getMaSV()
                    .equals(maSV)) {

                danhSachSinhVien.remove(i);

                break;
            }
        }

        // Xóa tất cả dòng của sinh viên
        for (int i = model.getRowCount() - 1; i >= 0; i--) {

            if (model.getValueAt(i, 0)
                    .toString()
                    .equals(maSV)) {

                model.removeRow(i);
            }
        }

        JOptionPane.showMessageDialog(
                this,
                "Xóa sinh viên thành công!"
        );

        btnLamMoiActionPerformed(null);

    }//GEN-LAST:event_btnXoaActionPerformed

    private void tableDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDiemMouseClicked
        // TODO add your handling code here:                                     

        int row = tableDiem.getSelectedRow();

        if (row == -1) {
            return;
        }

        // Hiển thị thông tin sinh viên
        txtMaSV.setText(model.getValueAt(row, 0).toString());
        txtTenSV.setText(model.getValueAt(row, 1).toString());

        // Hiển thị thông tin học phần
        txtTenHocPhan.setText(model.getValueAt(row, 2).toString());
        txtChuyenCan.setText(model.getValueAt(row, 3).toString());
        txtGiuaKy.setText(model.getValueAt(row, 4).toString());
        txtCuoiKy.setText(model.getValueAt(row, 5).toString());

        // Cho phép sửa điểm + tên học phần
        txtTenHocPhan.setEnabled(true);
        txtChuyenCan.setEnabled(true);
        txtGiuaKy.setEnabled(true);
        txtCuoiKy.setEnabled(true);

        // Không cho sửa mã sinh viên
        txtMaSV.setEnabled(false);

        // Cho phép sửa tên sinh viên
        txtTenSV.setEnabled(true);

        // Không cần nhập lại số lượng học phần
        txtSoLuongHocPhan.setEnabled(false);
    }//GEN-LAST:event_tableDiemMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed

        // Xóa các ô nhập
        txtMaSV.setText("");
        txtTenSV.setText("");
        txtSoLuongHocPhan.setText("");

        txtTenHocPhan.setText("");
        txtChuyenCan.setText("");
        txtGiuaKy.setText("");
        txtCuoiKy.setText("");

        soLuongDaNhap = 0;
        soLuongHocPhanCanNhap = 0;
        daNhapSoLuong = false;

        // Cho nhập sinh viên
        txtMaSV.setEnabled(true);
        txtTenSV.setEnabled(true);
        txtSoLuongHocPhan.setEnabled(true);

        // Khóa nhập học phần
        txtTenHocPhan.setEnabled(false);
        txtChuyenCan.setEnabled(false);
        txtGiuaKy.setEnabled(false);
        txtCuoiKy.setEnabled(false);

        btnThem.setEnabled(true);
        btnThem.setText("Thêm");

        tableDiem.clearSelection();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaiThucHanhNgay200826.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaiThucHanhNgay200826.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaiThucHanhNgay200826.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaiThucHanhNgay200826.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaiThucHanhNgay200826().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableDiem;
    private javax.swing.JTextField txtChuyenCan;
    private javax.swing.JTextField txtCuoiKy;
    private javax.swing.JTextField txtGiuaKy;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtSoLuongHocPhan;
    private javax.swing.JTextField txtTenHocPhan;
    private javax.swing.JTextField txtTenSV;
    // End of variables declaration//GEN-END:variables
}
